### ISSUE TITLE
Can't open example because of missed prefab

### ISSUE THREAD

**Issue by AGulev** [voxell-tech/GPUClothSimulationInUnity#1]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/2209596/85877951-3ba96e80-b7d8-11ea-9283-6676ca02a8a3.png">

**Comment by nixon-nyx** [comment]
Hi, you need to install blender in order to view the objects as the file type is .blender (i did not export as fbx for a reason, ill discuss later in my video series) : )

**Comment by AGulev** [comment]
Thank you! I'll try!
